spring:
  redis:
    host: 10.152.4.82
    port: 6379
    password: OWMyOTVmOTJhNzd
    timeout: 10000
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: true
    testWhileIdle: true

  datasource:
    url: jdbc:mysql://10.152.17.126:3306/promotion_sit?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: promotion_sit
    password: Dd^&wG4ij37
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 8080
  servlet:
    context-path: /mq

global-constants:
  orders-limit-per-day: 1000000
  app-id: app-id
  app-secret: app-secret
  mch-id: 1101101101
  api-key: 11011011011011011011011011011011
  notify-url: https://www.unknown7.xyz/mq/wx/paymentResult
  trade-type: JSAPI
